### ISSUE TITLE
Make artifacts available in maven central

### ISSUE THREAD

**Issue by francisdb** [moquette-io/moquette#61]
Depending on external repos is strongly discouraged here, would be nice if the artifacts would be available in maven central.
Since you are already using bintray this should not be a lot of work.
https://bintray.com/docs/usermanual/uploads/uploads_syncingartifactswithmavencentral.html

**Comment by andsel** [comment]
Done, version 0.8 is available on JCenter groupId:io.moquette artifactId:moquette-broker, version:0.8

**Comment by francisdb** [comment]
Still not available at maven central:
http://search.maven.org/#search%7Cga%7C1%7Cmoquette yields no results

**Comment by Macroz** [comment]
Would be nice to have the package in central.

Using http://jcenter.bintray.com/ works though.

**Comment by andsel** [comment]
We are gong to release just to one maven repository, and chosen is jcenter

**Comment by earcam** [comment]
Respectively, if there can be only one, then it should be the "one" - as in the default.
